spring:
  datasource:
    username: username
    password: password
    url: jdbc:mariadb://localhost:3306/example

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB102Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
